server:
  port: 6061
spring:
  application:
    name: turbine-rabbitmq
  rabbitmq:
    host: localhost
    username: admin
    password: 123456
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    hostname: localhost
    appname: turbine-rabbitmq
  client:
    service-url:
      defaultZone: http://localhost:9091/eureka
turbine:
  stream:
    destination: hystrixStreamOutput
