server:
  port: 7072
spring:
  application:
    name: consumer
eureka:
  instance:
    hostname: 192.168.1.101
    appname: consumer
  client:
    service-url:
      defaultZone: http://localhost:9091/eureka
feign:
  hystrix:
    enabled: true

