server:
  port: 7071
spring:
  application:
    name: consumer
eureka:
  instance:
    hostname: localhost
    appname: consumer
  client:
    service-url:
      defaultZone: http://localhost:9091/eureka
feign:
  hystrix:
    enabled: true
