server:
  port: 8082
spring:
  application:
    name: provider
eureka:
  instance:
    hostname: localhost
    appname: provider
  client:
    service-url:
      defaultZone: http://localhost:9091/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
